namespace SailorNumberGuessingGame.Shared.Models.Enums;
public enum CompareNumbersResultCode
{
  COMPARENUMBERS_PENDING,
  COMPARENUMBERS_SAME,

  COMPARENUMBERS_EXPEXTEDNUMBERFORMAT_NOT_CORRECT,
  COMPARENUMBERS_ENTEREDNUMBERFORMAT_NOT_CORRECT,
}
